const PROTOCOL = {
  PEER_JOIN: "peer-join",
  PEER_LEAVE: "peer-leave",
  PEER_EXIT: "peer-exit",
  PEER_LIST: "peer-list",
  OFFER: "offer",
  ANSWER: "answer",
  ICE_CANDIDATE: "ice-candidate",
  CHAT: "chat",
  REACTION: "reaction",
  POSITION: "position",
  PING: "ping",
  PONG: "pong",
  HEATMAP_SYNC: "heatmap-sync",
  ORGANIZER_BROADCAST: "organizer-broadcast",
  GET_REPLAY: "get-replay",
  REPLAY_DATA: "replay-data",
  SET_LATENCY: "set-latency",
  FORUM_MSG: "forum-msg",
  FORUM_COMMENT: "forum-comment",
  FORUM_SYNC_REQ: "forum-sync-req",
  FORUM_SYNC_RES: "forum-sync-res",
  GAME_INVITE: "game-invite",
  GAME_ACCEPT: "game-accept",
  GAME_REJECT: "game-reject",
  GAME_MOVE: "game-move",
  REACTION_READY: "reaction-ready",
  REACTION_GO: "reaction-go",
  REACTION_TAP: "reaction-tap",
  TRIVIA_START: "trivia-start",
  TRIVIA_ANSWER: "trivia-answer",
  ZONE_CHANGE: "zone-change",
  POS_SYNC: "pos-sync",
  UPDATE_POINTS: "update-points",
};

export default PROTOCOL;
